services:
  # Backend API Service
  - type: web
    name: todo-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: todo-mongodb
          property: connectionString

  # Frontend Web Service  
  - type: web
    name: todo-frontend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com

databases:
  # MongoDB Database
  - name: todo-mongodb
    plan: free